# Generated by Django 4.1.6 on 2023-10-28 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buraxilis11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=12)),
                ('soyad', models.CharField(max_length=12)),
                ('is_no', models.IntegerField()),
                ('tel_no', models.CharField(max_length=10)),
                ('sinif', models.CharField(choices=[('8', '8'), ('9', '9'), ('b', '10'), ('a', '11')], max_length=2)),
                ('bolme', models.CharField(choices=[('A', 'Azərbaycan'), ('R', 'Rus')], max_length=15)),
                ('cins', models.CharField(choices=[('K', 'Kişi'), ('Q', 'Qadın')], max_length=10)),
                ('variant', models.CharField(max_length=1)),
                ('x_dil', models.CharField(choices=[('I', 'İngilis dili'), ('F', 'Fransız dili'), ('A', 'Alman dili'), ('R', 'Rus dili')], max_length=15)),
                ('rayon', models.CharField(max_length=3)),
                ('mekteb', models.CharField(max_length=3)),
                ('f1_q', models.CharField(max_length=23)),
                ('f1_a4', models.FloatField(blank=True, null=True)),
                ('f1_a5', models.FloatField(blank=True, null=True)),
                ('f1_a6', models.FloatField(blank=True, null=True)),
                ('f1_a27', models.FloatField(blank=True, null=True)),
                ('f1_a28', models.FloatField(blank=True, null=True)),
                ('f1_a29', models.FloatField(blank=True, null=True)),
                ('f1_a30', models.FloatField(blank=True, null=True)),
                ('f1_d_q', models.IntegerField()),
                ('f1_d_a', models.FloatField(blank=True, null=True)),
                ('f2_q', models.CharField(max_length=20)),
                ('f2_a46', models.FloatField(blank=True, null=True)),
                ('f2_a47', models.FloatField(blank=True, null=True)),
                ('f2_a48', models.FloatField(blank=True, null=True)),
                ('f2_a49', models.FloatField(blank=True, null=True)),
                ('f2_a50', models.FloatField(blank=True, null=True)),
                ('f2_a56', models.FloatField(blank=True, null=True)),
                ('f2_a57', models.FloatField(blank=True, null=True)),
                ('f2_a58', models.FloatField(blank=True, null=True)),
                ('f2_a59', models.FloatField(blank=True, null=True)),
                ('f2_a60', models.FloatField(blank=True, null=True)),
                ('f2_d_q', models.IntegerField()),
                ('f2_d_a', models.FloatField(blank=True, null=True)),
                ('f3_q', models.CharField(max_length=13)),
                ('f3_k_a', models.CharField(max_length=34)),
                ('f3_a79', models.FloatField(blank=True, null=True)),
                ('f3_a80', models.FloatField(blank=True, null=True)),
                ('f3_a81', models.FloatField(blank=True, null=True)),
                ('f3_a82', models.FloatField(blank=True, null=True)),
                ('f3_a83', models.FloatField(blank=True, null=True)),
                ('f3_a84', models.FloatField(blank=True, null=True)),
                ('f3_a85', models.FloatField(blank=True, null=True)),
                ('f3_d_q', models.IntegerField()),
                ('f3_d_k', models.IntegerField()),
                ('f3_d_a', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsasSehife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', ckeditor.fields.RichTextField(blank=True, max_length=200)),
                ('elave', ckeditor.fields.RichTextField(blank=True, max_length=100)),
                ('elave1', ckeditor.fields.RichTextField(blank=True, max_length=100)),
                ('sekil', models.ImageField(upload_to='istedad_images/giris/')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_adi', models.CharField(max_length=50)),
                ('genis_melumat', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField()),
                ('sekil', models.ImageField(upload_to='istedad_images/kurslar/')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil_adi', models.CharField(blank=True, max_length=50)),
                ('sekil', models.ImageField(upload_to='istedad_images/media/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Muellim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('fenn', models.CharField(max_length=50)),
                ('aciqlama', ckeditor.fields.RichTextField(blank=True)),
                ('sekil', models.ImageField(upload_to='istedad_images/muellim/')),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saygac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=50)),
                ('cem', models.IntegerField()),
                ('suret', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('icon', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Serhler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=50)),
                ('yuksek_netice', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('aciqlama', models.TextField()),
                ('sekil', models.ImageField(null=True, upload_to='istedad_images/serhler/')),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinaqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinaq_adi', models.CharField(max_length=50)),
                ('sinaq_tarix', models.DateField(auto_now_add=True)),
                ('sinaq_nov', models.CharField(choices=[('asagisinif', 'Aşağı siniflər'), ('blok9_10', 'Blok 9 və 10-cu siniflər'), ('blok11', 'Blok 11-ci sinif'), ('buraxilis9', 'Buraxılış 9-cu sinif'), ('buraxilis10-11', 'Buraxılış 10 və 11-ci siniflər')], max_length=100, null=True)),
                ('sinaq_duzgun_cvb', models.TextField(blank=True, null=True)),
                ('sinaq_sagird_cvb', models.TextField(blank=True, null=True)),
                ('sinaq_sekil', models.ImageField(null=True, upload_to='istedad_images/sinaq/')),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Struktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezife', models.CharField(max_length=50)),
                ('ad_soyad', models.CharField(max_length=50)),
                ('elave', models.CharField(max_length=100)),
                ('sekil', models.ImageField(upload_to='istedad_images/struktur/')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tedbirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(auto_now_add=True)),
                ('basliq', models.CharField(max_length=100)),
                ('sekil', models.ImageField(upload_to='istedad_images/xeberler/')),
                ('aciqlama', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
