# Generated by Django 4.1.6 on 2023-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0003_alter_buraxilis11_f1_d_q_alter_buraxilis11_f2_d_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='is_no',
            field=models.CharField(max_length=6),
        ),
    ]
