# Generated by Django 4.1.6 on 2023-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0004_alter_buraxilis11_is_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buraxilis11',
            options={'ordering': ['ad']},
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='is_no',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
