# Generated by Django 4.1.6 on 2023-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0005_alter_buraxilis11_options_alter_buraxilis11_is_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraxilis11',
            name='sinaq_no',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
