# Generated by Django 4.1.6 on 2023-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0007_alter_buraxilis11_sinaq_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buraxilis11',
            options={'ordering': ['aad']},
        ),
        migrations.RenameField(
            model_name='buraxilis11',
            old_name='ad',
            new_name='aad',
        ),
    ]
