# Generated by Django 4.1.6 on 2023-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0008_alter_buraxilis11_options_rename_ad_buraxilis11_aad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buraxilis11',
            options={'ordering': ['-cem']},
        ),
        migrations.AddField(
            model_name='buraxilis11',
            name='cem',
            field=models.IntegerField(default=0),
        ),
    ]
