# Generated by Django 4.1.6 on 2023-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0009_alter_buraxilis11_options_buraxilis11_cem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraxilis11',
            name='d1_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buraxilis11',
            name='d2_q',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buraxilis11',
            name='d3_q',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
