# Generated by Django 4.1.6 on 2023-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0010_buraxilis11_d1_q_buraxilis11_d2_q_buraxilis11_d3_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='d1_q',
            field=models.CharField(max_length=23),
        ),
    ]
