# Generated by Django 4.1.6 on 2023-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0011_alter_buraxilis11_d1_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='is_no',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='sinaq_no',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
