# Generated by Django 4.1.6 on 2023-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0013_alter_buraxilis11_sinaq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='sinaq_no',
            field=models.CharField(max_length=100),
        ),
    ]
