# Generated by Django 4.1.6 on 2023-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0014_alter_buraxilis11_sinaq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='sinif',
            field=models.CharField(max_length=2),
        ),
    ]
