# Generated by Django 4.1.6 on 2023-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0015_alter_buraxilis11_sinif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f1_d_q',
        ),
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f2_d_q',
        ),
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f3_d_q',
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='bolme',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='x_dil',
            field=models.CharField(max_length=15),
        ),
    ]
