# Generated by Django 4.1.6 on 2023-10-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0016_remove_buraxilis11_f1_d_q_remove_buraxilis11_f2_d_q_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f1_d_a',
        ),
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f2_d_a',
        ),
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f3_d_a',
        ),
    ]
