# Generated by Django 4.1.6 on 2023-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0017_remove_buraxilis11_f1_d_a_remove_buraxilis11_f2_d_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buraxilis11',
            options={'ordering': ['cem']},
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='cem',
            field=models.FloatField(default=0),
        ),
    ]
