# Generated by Django 4.1.6 on 2023-10-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0018_alter_buraxilis11_options_alter_buraxilis11_cem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buraxilis11',
            options={'ordering': ['-cem']},
        ),
        migrations.AlterField(
            model_name='buraxilis11',
            name='cem',
            field=models.FloatField(),
        ),
    ]
