# Generated by Django 4.1.6 on 2023-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0020_buraxilis11_d3_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraxilis11',
            name='d3_k',
            field=models.CharField(max_length=30),
        ),
    ]
