# Generated by Django 4.1.6 on 2023-10-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0021_alter_buraxilis11_d3_k'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buraxilis11',
            name='f3_d_k',
        ),
    ]
