# Generated by Django 4.1.6 on 2023-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0022_remove_buraxilis11_f3_d_k'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsagiSinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinaq_no', models.CharField(max_length=100)),
                ('aad', models.CharField(max_length=12)),
                ('soyad', models.CharField(max_length=12)),
                ('is_no', models.CharField(max_length=6)),
                ('sinif', models.CharField(max_length=2)),
                ('d1_q', models.CharField(max_length=23)),
                ('f1_q', models.CharField(max_length=23)),
                ('d2_q', models.CharField(max_length=20)),
                ('f2_q', models.CharField(max_length=20)),
                ('d3_q', models.CharField(max_length=13)),
                ('f3_q', models.CharField(max_length=13)),
                ('cem', models.FloatField()),
            ],
        ),
    ]
