# Generated by Django 4.1.6 on 2023-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0023_asagisinif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asagisinif',
            name='cem',
            field=models.FloatField(default=0),
        ),
    ]
