# Generated by Django 4.1.6 on 2023-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0024_alter_asagisinif_cem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asagisinif',
            name='d1_q',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='d2_q',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='d3_q',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f1_q',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f2_q',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f3_q',
            field=models.CharField(max_length=20),
        ),
    ]
