# Generated by Django 4.1.6 on 2023-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0025_alter_asagisinif_d1_q_alter_asagisinif_d2_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asagisinif',
            name='d1_q',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='d2_q',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='d3_q',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f1_q',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f2_q',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='asagisinif',
            name='f3_q',
            field=models.CharField(max_length=30),
        ),
    ]
