# Generated by Django 4.1.6 on 2023-11-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0026_alter_asagisinif_d1_q_alter_asagisinif_d2_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asagisinif',
            name='is_no',
            field=models.CharField(max_length=7),
        ),
    ]
