# Generated by Django 4.1.6 on 2023-11-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0027_alter_asagisinif_is_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asagisinif',
            options={'ordering': ['-cem']},
        ),
        migrations.AddField(
            model_name='asagisinif',
            name='ata_adi',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
