# Generated by Django 4.1.6 on 2023-11-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0028_alter_asagisinif_options_asagisinif_ata_adi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asagisinif',
            name='ata_adi',
            field=models.CharField(max_length=12),
        ),
    ]
