# Generated by Django 4.1.6 on 2023-12-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0030_blok11_alter_sinaqlar_sinaq_adi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok11',
            name='aad',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='blok',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='cem',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='is_no',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='sinaq_no',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='sinif',
        ),
        migrations.RemoveField(
            model_name='blok11',
            name='soyad',
        ),
    ]
