# Generated by Django 4.1.6 on 2023-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0031_remove_blok11_aad_remove_blok11_blok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok11',
            name='aad',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='blok',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='cem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='d1_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='d2_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='d3_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f1_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f1_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f2_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f2_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f3_k_a',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='f3_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='is_no',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='sinaq_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='sinif',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='soyad',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
