# Generated by Django 4.1.6 on 2023-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0032_blok11_aad_blok11_blok_blok11_cem_blok11_d1_k_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok11',
            name='d1_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='d2_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blok11',
            name='d3_q',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
    ]
