# Generated by Django 4.1.6 on 2023-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0033_blok11_d1_q_blok11_d2_q_blok11_d3_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok11',
            name='d1_k_a',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='blok11',
            name='d2_k_a',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='blok11',
            name='d3_k_a',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='blok11',
            name='f1_k_a',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='blok11',
            name='f2_k_a',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='blok11',
            name='f3_k_a',
            field=models.CharField(max_length=45),
        ),
    ]
