# Generated by Django 4.1.6 on 2023-12-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0034_alter_blok11_d1_k_a_alter_blok11_d2_k_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blok11',
            options={'ordering': ['-cem']},
        ),
    ]
