# Generated by Django 4.1.6 on 2023-12-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0035_alter_blok11_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok11',
            name='f1_28',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f1_29',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f1_30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f2_28',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f2_29',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f2_30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f3_28',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f3_29',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blok11',
            name='f3_30',
            field=models.IntegerField(default=0),
        ),
    ]
