# Generated by Django 4.1.6 on 2023-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0036_blok11_f1_28_blok11_f1_29_blok11_f1_30_blok11_f2_28_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok9_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinaq_no', models.CharField(max_length=100)),
                ('aad', models.CharField(max_length=12)),
                ('soyad', models.CharField(max_length=12)),
                ('is_no', models.CharField(max_length=6)),
                ('sinif', models.CharField(max_length=2)),
                ('blok', models.CharField(max_length=1)),
                ('f1_q', models.CharField(max_length=22)),
                ('f2_q', models.CharField(max_length=22)),
                ('f3_q', models.CharField(max_length=22)),
                ('f1_k_a', models.CharField(max_length=45)),
                ('f2_k_a', models.CharField(max_length=45)),
                ('f3_k_a', models.CharField(max_length=45)),
                ('d1_q', models.CharField(max_length=22)),
                ('d2_q', models.CharField(max_length=22)),
                ('d3_q', models.CharField(max_length=22)),
                ('d1_k_a', models.CharField(max_length=45)),
                ('d2_k_a', models.CharField(max_length=45)),
                ('d3_k_a', models.CharField(max_length=45)),
                ('cem', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-cem'],
            },
        ),
    ]
