# Generated by Django 4.1.6 on 2023-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0037_blok9_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok9_10',
            name='ata_adi',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
