# Generated by Django 4.1.6 on 2023-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0038_blok9_10_ata_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok9_10',
            name='fenn3',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
