# Generated by Django 4.1.6 on 2023-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0039_blok9_10_fenn3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blok11',
            name='fenn3',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
