# Generated by Django 4.1.6 on 2023-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0040_blok11_fenn3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok9_10',
            name='sinif',
            field=models.CharField(choices=[('1', 11), ('0', 10)], max_length=2),
        ),
    ]
