# Generated by Django 4.1.6 on 2023-12-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0041_alter_blok9_10_sinif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blok9_10',
            name='sinif',
            field=models.CharField(max_length=2),
        ),
    ]
