# Generated by Django 4.1.6 on 2023-12-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0042_alter_blok9_10_sinif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinaqlar',
            options={'ordering': ['-id']},
        ),
    ]
