# Generated by Django 4.1.6 on 2023-12-28 06:35

from django.db import migrations, models
import istedadapp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('istedad', '0043_alter_sinaqlar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esassehife',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/giris/'),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/kurslar/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/media/'),
        ),
        migrations.AlterField(
            model_name='muellim',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/muellim/'),
        ),
        migrations.AlterField(
            model_name='serhler',
            name='sekil',
            field=models.ImageField(null=True, storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/serhler/'),
        ),
        migrations.AlterField(
            model_name='sinaqlar',
            name='sinaq_sekil',
            field=models.ImageField(null=True, storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/sinaq/'),
        ),
        migrations.AlterField(
            model_name='struktur',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/struktur/'),
        ),
        migrations.AlterField(
            model_name='tedbirler',
            name='sekil',
            field=models.ImageField(storage=istedadapp.storage_backends.PublicMediaStorage(), upload_to='istedad_images/xeberler/'),
        ),
    ]
