# Generated by Django 3.2.16 on 2023-01-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQeydiyyatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('telNo', models.CharField(max_length=50)),
                ('rayon', models.CharField(max_length=50)),
                ('mekteb', models.CharField(max_length=50)),
                ('sinif', models.CharField(max_length=50)),
                ('blok', models.CharField(max_length=50)),
                ('xdil', models.CharField(max_length=50)),
            ],
        ),
    ]
