# Generated by Django 3.2.16 on 2023-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qeydiyyat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminqeydiyyatform',
            name='telNo_basliq',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
