# Generated by Django 4.1.6 on 2023-02-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qeydiyyat', '0002_adminqeydiyyatform_telno_basliq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSinaqQeydiyyatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('telNo_basliq', models.CharField(max_length=50, null=True)),
                ('telNo', models.CharField(max_length=50)),
                ('rayon', models.CharField(max_length=50)),
                ('mekteb', models.CharField(max_length=50)),
                ('sinif', models.CharField(max_length=50)),
                ('blok', models.CharField(max_length=50)),
                ('xdil', models.CharField(max_length=50)),
            ],
        ),
    ]
