# Generated by Django 4.1.6 on 2023-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qeydiyyat', '0003_adminsinaqqeydiyyatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminElaqeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('telNo', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
