name: Deploy to Web Server

on:
  push:
    branches:
      - master  # Change this to your main branch
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{secrets.SSH_HOST}} > ~/.ssh/known_hosts

    - name: Deploy to Web Server
      run: |
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
        git checkout master
        git pull
        sudo systemctl daemon-reload
        sudo systemctl disable gunicorn
        sudo systemctl enable gunicorn
        sudo systemctl start gunicorn
        sudo nginx -t
        sudo systemctl restart nginx
